name: Python Black Formatter and Docker Image CI

on:
  push:
    branches: [ '**' ]  # Triggers on push to any branch
  pull_request:
    branches: [ '**' ]  # Triggers on pull requests to any branch

jobs:
  format:
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' # Specify the Python version.

      - name: Install black
        run: pip install black

      - name: Run black format
        run: black .
        id: format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Apply auto-formatting
            branch: ${{ github.head_ref }}
            file_pattern: '**/*.py'

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker image tag
        id: docker_tag
        run: echo "DOCKER_TAG=my-image-name:$(date +%s)" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.DOCKER_TAG }}

      - name: Run the Python script
        run: docker run ${{ env.DOCKER_TAG }} python3 src/train.py --dataset_name mnist --num_episodes 5 --train_limit 100
